# Generated by Django 2.2.1 on 2019-05-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
