# Generated by Django 2.2.1 on 2019-05-26 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='TeacherOccupy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=32)),
                ('start_time', models.DateTimeField(default=None)),
                ('end_time', models.DateTimeField(default=None)),
                ('subject', models.CharField(max_length=32)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.Teacher')),
            ],
        ),
    ]
